### ISSUE TITLE
Adjust Conditions

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#338]
Conditions currently are still in the "classic way" but should be moved to the new rules.
Else in TYPO3 Version 9 the log is flooded with Messages like this:
```
Mon, 15 Oct 2018 19:50:02 +0200 [WARNING] request="880d766943f4a" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = LIT:0 < 0"}
Mon, 15 Oct 2018 19:50:02 +0200 [WARNING] request="880d766943f4a" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed, fallback kicks in. It looks like an old condition with only one equal sign. - {"expression":"globalVar = GP:type = 31311"}
```
[Here the "new rules"](https://docs.typo3.org/typo3cms/TyposcriptReference/Conditions/Reference.html) for conditions.

**Comment by einpraegsam** [comment]
What about compatibility for TYPO3 8.7?

**Comment by DavidBruchmann** [comment]
TYPO3 8.7 should support the new syntax already.

**Comment by einpraegsam** [comment]
ok so thx for the note. Interested in doing a pr?

**Comment by DavidBruchmann** [comment]
Yeah ok, working it anyway

**Comment by DavidBruchmann** [comment]
I mistaked, the new syntax never seems being known yet in 8,7.
So the update will be for 9.4+ only

**Comment by tmotyl** [comment]
Alternatively the v9 compatible TYPOScript could be provided as separate static templates

**Comment by vertexvaar** [comment]
Hi,

starting with v9 TYPO3 will log legacy conditions like `[globalVar = LIT:0 < {$plugin.tx_powermail.settings.styles.bootstrap.important}]`. We are currently facing this issue on a customers page that is producing gigabytes of logs because of legacy conditions in various extensions.
I disabled the Strict TypoScript feature toggle in the TYPO3 Settings Module to prevent further logging, but this topic should be addressed in a timely manner. Since TYPO3 v10 will be released in April and does not support the old syntax i think it is time to re-evaluate and re-open this issue.

With Regards

**Comment by einpraegsam** [comment]
Conditions and a lot more stuff was already updated for TYPO3 10 in branch feature/8.0.0 (but this branch is net yet ready)

**Comment by nebrot** [comment]
@einpraegsam This is still a problem in TYPO3 10.3 with Powermail 8.1.0. We don't use Bootstrap and this is flooding our TYPO3-logs:

> [ERROR] request="3c74152e654b8" component="TYPO3.CMS.Frontend.Configuration.TypoScript.ConditionMatching.ConditionMatcher": Expression could not be parsed. - {"expression":"{$plugin.tx_powermail.settings.styles.bootstrap.important} == 1"}

I have added this constant `plugin.tx_powermail.settings.styles.bootstrap.important = 0` in `/Configuration/TypoScript/Main/constants.typoscript`, now there seems no more error.
