### ISSUE TITLE
CRITICAL: Duplicate variable names auto assigned (not manually fixable)

### ISSUE THREAD

**Issue by DavidR93** [einpraegsam/powermail#787]
When creating a form (explicitly when creating the fields) duplicate variable names (auto_marker) are assigned. This happens even though the fields have different titles. 

Assigning own variable names (own_marker_select) to work around the problem unfortunately has no success either. After saving, the self-assigned values are gone.

TYPO3: 11.5.12
PHP: 8.1.0
Powermail: 10.4.1

**Comment by einpraegsam** [comment]
I played a bit and could reproduce the issue. I will provide a fix asap.

**Comment by einpraegsam** [comment]
Hi @DavidR93 I just pushed a fix to develop branch. Are you able to test the latest commits?

**Comment by DavidR93** [comment]
> Hi @DavidR93 I just pushed a fix to develop branch. Are you able to test the latest commits?

I will test the changes tomorrow morning and report back afterwards.

**Comment by DavidR93** [comment]
Unfortunately, I encountered a bug while testing. 
Steps for reproduction:

1. create form
2. create page
3. create field
4. set checkmark at "mandatory field"
5. save

Cannot assign int to property In2code\Powermail\Domain\Model\Field::$page of type ?In2code\Powermail\Domain\Model\Page
in /var/www/html/public/typo3/sysext/extbase/Classes/DomainObject/AbstractDomainObject.php line 116
in /var/www/html/public/typo3conf/ext/powermail/Classes/Hook/CreateMarker.php line 247

TYPO3: 11.5.12
PHP: 8.1.0
Powermail: dev-develop

**Comment by dennismetz** [comment]
I can also still reproduce the error.
Whereas 4. in the above list for me was to make a select field out of a text field and then save it.

TYPO3: 11.5.12
PHP: 8.1.7
Powermail: dev-develop

**Comment by DavidR93** [comment]
> I can also still reproduce the error. Whereas 4. in the above list for me was to make a select field out of a text field and then save it.
> 
> TYPO3: 11.5.12 PHP: 8.1.7 (7.4.30) Powermail: dev-develop
> 
> Edit: A similar error occurs under PHP7.4. Typed property In2code\Powermail\Domain\Model\Field::$page must be an instance of In2code\Powermail\Domain\Model\Page or null, int used

I have tested a little and can confirm that.

TYPO3: 11.5.12
PHP: 8.1.0
Powermail: dev-develop

**Comment by einpraegsam** [comment]
Sorry, that this critical issue is still open, but it was a hard week so far.
I just changed the last property. 
Anyone who wants to test again?

**Comment by DavidR93** [comment]
> Sorry, that this critical issue is still open, but it was a hard week so far. I just changed the last property. Anyone who wants to test again?

Don't worry about that :) I have just tested and encountered the following errors:

**1. When I try to access the form overview in the powermail backend module I get the following error:**
TYPO3\CMS\Extbase\Persistence\Generic\Mapper\Exception\UnknownPropertyTypeException
The type of property In2code\Powermail\Domain\Model\Field::page could not be identified, therefore the desired value (NULL) cannot be mapped onto it. The type of a class property is usually defined via php doc blocks. Make sure the property has a valid @var tag set which defines the type.

**2. When I try to save an existing form (list view) I get the following error:**
Cannot assign int to property In2code\Powermail\Domain\Model\Field::$multiselect of type bool
in /var/www/html/public/typo3/sysext/extbase/Classes/DomainObject/AbstractDomainObject.php line 116
in /var/www/html/public/typo3conf/ext/powermail/Classes/Hook/CreateMarker.php line 246

**Comment by einpraegsam** [comment]
Thx for your feedback, I changed the commit a bit and hope that now everything works as expected?

**Comment by einpraegsam** [comment]
I will release a new version that hopefully fixes this issue :)
